# Generated by Django 5.2.17 on 2026-08-05 11:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_artistauth_address_en_artistauth_biography_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playconfiguration',
            name='minimum_payout_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.01'),
                help_text='Minimum withdrawable artist balance required to submit a payout request.',
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
            ),
        ),
    ]
