# Base URL is : https://api.sedabox.com/
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserProfileView,
    UserImageProfileView,
    UserImageProfileDetailView,
    InitialCheckView,
    NotificationSettingUpdateView,
    StreamQualityUpdateView,
    UserFollowView,
    LikedSongsView,
    LikedSongsSearchView,
    LikedAlbumsSearchView,
    LikedPlaylistsSearchView,
    LikedAlbumsView,
    LikedPlaylistsView,
    MyArtistsView,
    MyLibraryView,
    UserHistoryView,
    UserHistoryDeleteView,
    DownloadHistoryDeleteView,
    UserHistorySearchView,
    DownloadHistoryView,
    UserProfilePublicView,
    SedaBoxProfileView,
    R2UploadView,
    SongUploadView,
    ArtistListView,
    ArtistDetailView,
    ArtistHomeView,
    ArtistAnalyticsView,
    ArtistLiveListenersView,
    ArtistLiveListenersPollView,
    ArtistSongsManagementView,
    ArtistAlbumsManagementView,
    DepositRequestView,
    ArtistWalletView,
    ArtistFinanceView,
    ArtistFinanceSongsView,
    ArtistSettingsView,
    ArtistChangePasswordView,
    AlbumListView,
    AlbumDetailView,
    AlbumLikeView,
    GenreListView,
    GenreDetailView,
    MoodListView,
    MoodDetailView,
    TagListView,
    TagDetailView,
    SubGenreListView,
    SubGenreDetailView,
    SongListView,
    SongDetailView,
    SongLikeView,
    SongIncrementPlaysView,
    SongStreamListView,
    UnwrapStreamView,
    StreamShortRedirectView,
    BannerAdView,
    AdSubmitView,
    PlayCountView,
    UserPlaylistListCreateView,
    UserPlaylistDetailView,
    UserPlaylistAddSongView,
    UserPlaylistRemoveSongView,
    UserPlaylistLikeView,
    UserRecommendationView,
    DiscoveriesView,
    LatestReleasesView,
    PopularArtistsView,
    PopularAlbumsView,
    WeeklyTopSongsView,
    WeeklyTopArtistsView,
    WeeklyTopAlbumsView,
    DailyTopSongsView,
    DailyTopArtistsView,
    DailyTopAlbumsView,
    HomeSummaryView,
    PlaylistRecommendationsView,
    PlaylistRecommendationDetailView,
    PlaylistDetailView,
    PlaylistRecommendationLikeView,
    PlaylistRecommendationSaveView,
    PremiumPlanPriceView,
    PlaylistSaveToggleView,
    SearchView,
    EventPlaylistView,
    EventPlaylistDetailView,
    SearchSectionListView,
    SearchSectionDetailView,
    PlaylistLikeView,
    RulesListCreateView,
    RulesDetailView,
    RulesLatestView,
    ReportCreateView,
    NotificationListView,
    NotificationMarkReadView,
)
from .admin_views import (
    AdminUserListView,
    AdminUserDetailView,
    AdminUserBanView,
    AdminArtistListView,
    AdminArtistDetailView,
    AdminPendingArtistListView,
    AdminPendingArtistDetailView,
    AdminHomeSummaryView,
    AdminUserSearchView,
    AdminSongListView,
    AdminSongDetailView,
    AdminReportListView,
    AdminReportDetailView,
    AdminAlbumListView,
    AdminAlbumDetailView,
    AdminAlbumSongActionView,
    AdminPlayConfigurationView,
    AdminBannerAdListView,
    AdminBannerAdDetailView,
    AdminAudioAdListView,
    AdminAudioAdDetailView,
    AdminFinanceSummaryView,
    AdminPaymentTransactionListView,
    AdminDepositRequestListView,
    AdminSearchSectionListView,
    AdminSearchSectionDetailView,
    AdminEventPlaylistListView,
    AdminEventPlaylistDetailView,
    AdminPlaylistListView,
    AdminPlaylistDetailView,
    AdminEmployeeListView,
    AdminEmployeeDetailView,
)
from .auth_views import (
    AuthRegisterView,
    AuthVerifyView,
    LoginPasswordView,
    LoginOtpRequestView,
    LoginOtpVerifyView,
    ArtistAuthView,
    ForgotPasswordView,
    PasswordResetView,
    ChangePasswordView,
    TokenRefreshView as LocalTokenRefreshView,
    LogoutView,
    SessionListView,
    SessionRevokeView,
    SessionRevokeOtherView,
)
from rest_framework_simplejwt.views import TokenRefreshView

# Create router for remaining viewsets (if any)
router = DefaultRouter()

urlpatterns = [
    # --- Authentication Endpoints (Shared by User and Artist Apps) ---
    path('auth/register/', AuthRegisterView.as_view(), name='auth_register'),
    path('auth/verify/', AuthVerifyView.as_view(), name='auth_verify'),
    path('auth/login/password/', LoginPasswordView.as_view(), name='auth_login_password'),
    path('auth/login/otp/request/', LoginOtpRequestView.as_view(), name='auth_login_otp_request'),
    path('auth/login/otp/verify/', LoginOtpVerifyView.as_view(), name='auth_login_otp_verify'),
    path('auth/password/forgot/', ForgotPasswordView.as_view(), name='auth_password_forgot'),
    path('auth/password/reset/', PasswordResetView.as_view(), name='auth_password_reset'),
    path('auth/password/change/', ChangePasswordView.as_view(), name='auth_password_change'),
    path('auth/token/refresh/', LocalTokenRefreshView.as_view(), name='auth_token_refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth_logout'),
    path('auth/sessions/', SessionListView.as_view(), name='session_list'),
    path('auth/sessions/<int:pk>/revoke/', SessionRevokeView.as_view(), name='session_revoke'),
    path('auth/sessions/revoke-others/', SessionRevokeOtherView.as_view(), name='session_revoke_others'),
    
    # ---  Profile Page Endpoints ---
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile/image/', UserImageProfileView.as_view(), name='user_image_profile'),
    path('profile/image/delete/', UserImageProfileDetailView.as_view(), name='user_image_profile_delete'),
    path('profile/initial-check/', InitialCheckView.as_view(), name='initial_check'),
    path('profile/settings/notifications/', NotificationSettingUpdateView.as_view(), name='user_notification_settings'),
    path('profile/settings/stream-quality/', StreamQualityUpdateView.as_view(), name='user_stream_quality_settings'),
    path('profile/liked-songs/', LikedSongsView.as_view(), name='liked_songs'),
    path('profile/liked-songs/search/', LikedSongsSearchView.as_view(), name='liked_songs_search'),
    path('profile/liked-albums/search/', LikedAlbumsSearchView.as_view(), name='liked_albums_search'),
    path('profile/liked-playlists/search/', LikedPlaylistsSearchView.as_view(), name='liked_playlists_search'),
    path('profile/liked-albums/', LikedAlbumsView.as_view(), name='liked_albums'),
    path('profile/liked-playlists/', LikedPlaylistsView.as_view(), name='liked_playlists'),
    path('profile/my-artists/', MyArtistsView.as_view(), name='my_artists'),
    path('profile/history/', UserHistoryView.as_view(), name='user_history_list'),
    path('profile/history/<int:pk>/', UserHistoryDeleteView.as_view(), name='user_history_delete'),
    path('profile/history/search/', UserHistorySearchView.as_view(), name='user_history_search'),
    path('profile/downloads/', DownloadHistoryView.as_view(), name='user_download_history'),
    path('profile/downloads/<int:pk>/', DownloadHistoryDeleteView.as_view(), name='download_history_delete'),
    path('profile/u/<str:unique_id>/', UserProfilePublicView.as_view(), name='user_public_profile'),
    path('profile/sedabox/', SedaBoxProfileView.as_view(), name='sedabox_profile'),
    
    path('profile/user-playlists/', UserPlaylistListCreateView.as_view(), name='user_playlist_list_create'),
    path('profile/user-playlists/<int:pk>/', UserPlaylistDetailView.as_view(), name='user_playlist_detail'),
    path('profile/user-playlists/<int:pk>/add-song/', UserPlaylistAddSongView.as_view(), name='user_playlist_add_song'),
    path('profile/user-playlists/<int:pk>/remove-song/<int:song_id>/', UserPlaylistRemoveSongView.as_view(), name='user_playlist_remove_song'),
    path('profile/user-playlists/<int:pk>/like/', UserPlaylistLikeView.as_view(), name='user_playlist_like'),
    
    # Library page endpoint
    path('my-library/', MyLibraryView.as_view(), name='my_library'),

    # Home Page Endpoints
    path('home/summary/', HomeSummaryView.as_view(), name='home_summary'),
    path('home/songs-recommendations/', UserRecommendationView.as_view(), name='user_recommendations'),
    path('home/discoveries/', DiscoveriesView.as_view(), name='user_discoveries'),
    path('home/latest-releases/', LatestReleasesView.as_view(), name='user_latest_releases'),
    path('home/popular-artists/', PopularArtistsView.as_view(), name='user_popular_artists'),
    path('home/popular-albums/', PopularAlbumsView.as_view(), name='user_popular_albums'),
    path('home/weekly-top-songs-global/', WeeklyTopSongsView.as_view(), name='user_weekly_top_songs_global'),
    path('home/weekly-top-artists-global/', WeeklyTopArtistsView.as_view(), name='user_weekly_top_artists_global'),
    path('home/weekly-top-albums-global/', WeeklyTopAlbumsView.as_view(), name='user_weekly_top_albums_global'),
    path('home/daily-top-songs-global/', DailyTopSongsView.as_view(), name='user_daily_top_songs_global'),
    path('home/daily-top-artists-global/', DailyTopArtistsView.as_view(), name='user_daily_top_artists_global'),
    path('home/daily-top-albums-global/', DailyTopAlbumsView.as_view(), name='user_daily_top_albums_global'),
    path('home/playlist-recommendations/', PlaylistRecommendationsView.as_view(), name='user_playlist_recommendations'),
    path('home/playlist-recommendations/<str:unique_id>/', PlaylistRecommendationDetailView.as_view(), name='user_playlist_recommendation_detail'),
    path('home/playlist-recommendations/<str:unique_id>/like/', PlaylistRecommendationLikeView.as_view(), name='user_playlist_recommendation_like'),
    path('home/playlist-recommendations/<str:unique_id>/save/', PlaylistRecommendationSaveView.as_view(), name='user_playlist_recommendation_save'),
    
    # Utility , DetailScreens & action Endpoints 
    path('follow/', UserFollowView.as_view(), name='user_follow'),
    path('artists/', ArtistListView.as_view(), name='artist_list'),
    path('artists/<int:pk>/', ArtistDetailView.as_view(), name='artist_detail'),
    path('albums/<int:pk>/', AlbumDetailView.as_view(), name='album_detail'),
    path('albums/<int:pk>/like/', AlbumLikeView.as_view(), name='album_like'),
    path('songs/<int:pk>/', SongDetailView.as_view(), name='song_detail'),
    path('songs/<int:pk>/like/', SongLikeView.as_view(), name='song_like'),
    path('stream/s/<str:token>/', StreamShortRedirectView.as_view(), name='stream-short'),
    path('playlists/<int:pk>/', PlaylistDetailView.as_view(), name='playlist_detail'),
    path('playlists/<int:pk>/like/', PlaylistLikeView.as_view(), name='playlist_like'),
    path('playlists/<int:pk>/save/', PlaylistSaveToggleView.as_view(), name='playlist_save_toggle'),
    path('play/count/', PlayCountView.as_view(), name='play_count'),
    path('ads/banner/', BannerAdView.as_view(), name='banner_ad'),
    path('ads/submit/', AdSubmitView.as_view(), name='ad_submit'),
    path('rules/latest/', RulesLatestView.as_view(), name='rules_latest'),
    path('notifications/', NotificationListView.as_view(), name='notification_list'),
    path('notifications/read/', NotificationMarkReadView.as_view(), name='notification_mark_all_read'),
    path('notifications/<int:pk>/read/', NotificationMarkReadView.as_view(), name='notification_mark_read'),
    path('reports/', ReportCreateView.as_view(), name='report_create'),


    # --- Artist App Endpoints ---
    path('artist/home/', ArtistHomeView.as_view(), name='artist_home'),
    path('artist/analytics/', ArtistAnalyticsView.as_view(), name='artist_analytics'),
    path('artist/live-listeners/', ArtistLiveListenersView.as_view(), name='artist_live_listeners'),
    path('artist/live-listeners/poll/', ArtistLiveListenersPollView.as_view(), name='artist_live_listeners_poll'),
    path('artist/songs/', ArtistSongsManagementView.as_view(), name='artist_songs_management'),
    path('artist/songs/upload/', ArtistSongsManagementView.as_view(), name='artist_songs_upload'),
    path('artist/songs/<int:pk>/', ArtistSongsManagementView.as_view(), name='artist_songs_detail'),
    path('artist/albums/', ArtistAlbumsManagementView.as_view(), name='artist_albums_management'),
    path('artist/albums/<int:pk>/', ArtistAlbumsManagementView.as_view(), name='artist_albums_detail'),
    path('artist/deposit-request/', DepositRequestView.as_view(), name='artist_deposit_request'),
    path('artist/wallet/', ArtistWalletView.as_view(), name='artist_wallet'),
    path('artist/finance/', ArtistFinanceView.as_view(), name='artist_finance'),
    path('artist/finance/songs/', ArtistFinanceSongsView.as_view(), name='artist_finance_songs'),
    path('artist/auth/', ArtistAuthView.as_view(), name='artist_auth'),
    path('artist/settings/', ArtistSettingsView.as_view(), name='artist_settings'),
    path('artist/settings/password/', ArtistChangePasswordView.as_view(), name='artist_change_password'),
    

    

    # --- Classification
    path('genres/', GenreListView.as_view(), name='genre_list'),
    path('genres/<int:pk>/', GenreDetailView.as_view(), name='genre_detail'),
    path('subgenres/', SubGenreListView.as_view(), name='subgenre_list'),
    path('subgenres/<int:pk>/', SubGenreDetailView.as_view(), name='subgenre_detail'),
    path('moods/', MoodListView.as_view(), name='mood_list'),
    path('moods/<int:pk>/', MoodDetailView.as_view(), name='mood_detail'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tags/<int:pk>/', TagDetailView.as_view(), name='tag_detail'),

    
    # --- Search Page Endpoints ---
    path('search/event-playlists/', EventPlaylistView.as_view(), name='event_playlist_list'),
    path('search/event-playlists/<int:pk>/', EventPlaylistDetailView.as_view(), name='event_playlist_detail'),
    path('search/sections/', SearchSectionListView.as_view(), name='search_section_list'),
    path('search/sections/<int:pk>/', SearchSectionDetailView.as_view(), name='search_section_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('plans/premium/price/', PremiumPlanPriceView.as_view(), name='premium_plan_price'),

    # --- Admin App Endpoints ---
    path('admin/users/', AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='admin_user_detail'),
    path('admin/users/ban/', AdminUserBanView.as_view(), name='admin_user_ban'),
    path('admin/artists/', AdminArtistListView.as_view(), name='admin_artist_list'),
    path('admin/artists/<int:pk>/', AdminArtistDetailView.as_view(), name='admin_artist_detail'),
    path('admin/pend_artists/', AdminPendingArtistListView.as_view(), name='admin_pending_artist_list'),
    path('admin/pend_artists/<int:pk>/', AdminPendingArtistDetailView.as_view(), name='admin_pending_artist_detail'),
    path('admin/home-summary/', AdminHomeSummaryView.as_view(), name='admin_home_summary'),
    path('admin/users/search/', AdminUserSearchView.as_view(), name='admin_user_search'),
    path('admin/songs/', AdminSongListView.as_view(), name='admin_song_list'),
    path('admin/songs/<int:pk>/', AdminSongDetailView.as_view(), name='admin_song_detail'),
    path('admin/reports/', AdminReportListView.as_view(), name='admin_report_list'),
    path('admin/reports/<int:pk>/', AdminReportDetailView.as_view(), name='admin_report_detail'),
    path('admin/albums/', AdminAlbumListView.as_view(), name='admin_album_list'),
    path('admin/albums/<int:pk>/', AdminAlbumDetailView.as_view(), name='admin_album_detail'),
    path('admin/albums/<int:album_id>/songs/<int:song_id>/', AdminAlbumSongActionView.as_view(), name='admin_album_song_action'),
    path('admin/pap-settings/', AdminPlayConfigurationView.as_view(), name='admin_pap_settings'),
    path('admin/ads/banners/', AdminBannerAdListView.as_view(), name='admin_banner_ad_list'),
    path('admin/ads/banners/<int:pk>/', AdminBannerAdDetailView.as_view(), name='admin_banner_ad_detail'),
    path('admin/ads/audio/', AdminAudioAdListView.as_view(), name='admin_audio_ad_list'),
    path('admin/ads/audio/<int:pk>/', AdminAudioAdDetailView.as_view(), name='admin_audio_ad_detail'),
    path('admin/finance/', AdminFinanceSummaryView.as_view(), name='admin_finance_summary'),
    path('admin/finance/transactions/', AdminPaymentTransactionListView.as_view(), name='admin_payment_transaction_list'),
    path('admin/finance/deposits/', AdminDepositRequestListView.as_view(), name='admin_deposit_request_list'),
    path('admin/sections/', AdminSearchSectionListView.as_view(), name='admin_search_section_list'),
    path('admin/sections/<int:pk>/', AdminSearchSectionDetailView.as_view(), name='admin_search_section_detail'),
    path('admin/event-playlist/', AdminEventPlaylistListView.as_view(), name='admin_event_playlist_list'),
    path('admin/event-playlist/<int:pk>/', AdminEventPlaylistDetailView.as_view(), name='admin_event_playlist_detail'),
    path('admin/playlists/', AdminPlaylistListView.as_view(), name='admin_playlist_list'),
    path('admin/playlists/<int:pk>/', AdminPlaylistDetailView.as_view(), name='admin_playlist_detail'),
    path('admin/employees/', AdminEmployeeListView.as_view(), name='admin_employee_list'),
    path('admin/employees/<int:pk>/', AdminEmployeeDetailView.as_view(), name='admin_employee_detail'),
    path('admin/rules/', RulesListCreateView.as_view(), name='rules_list_create'),
    path('admin/rules/<int:pk>/', RulesDetailView.as_view(), name='rules_detail'),
]

